-- Cria o schema e a tabela das GTAs (uma linha por guia).
-- Rode no SQL Editor do Supabase (ou pelo VS Code).
create schema if not exists adagri;

create table if not exists adagri.gta (
  numerogta bigint primary key,
  seriegta text,
  dataemissao date not null,
  tipotransito text,
  finalidade text,
  especie text,
  colmeia bigint,
  rainha bigint,
  ovoscistossementesesporos bigint,
  jovens bigint,
  adulto bigint,
  femeaacima6meses bigint,
  machoacima6meses bigint,
  femeaate6meses bigint,
  machoate6meses bigint,
  naodestinadasaproducaoornamentaissilvestresovosferteis bigint,
  naodestinadasaproducaoornamentaissilvestresadulto bigint,
  naodestinadasaproducaoornamentaissilvestresoutrasespecies bigint,
  femea0ate12meses bigint,
  macho0ate12meses bigint,
  macho13ate24meses bigint,
  femea13ate24meses bigint,
  macho25ate36meses bigint,
  femea25ate36meses bigint,
  machoacima36meses bigint,
  femeaacima36meses bigint,
  larva bigint,
  poslarva bigint,
  cistos bigint,
  todos bigint,
  capivara bigint,
  ate12mesesmacho bigint,
  ate12mesesfemea bigint,
  acima12mesesmacho bigint,
  acima12mesesfemea bigint,
  alevinojuvenil bigint,
  ovosembrionarios bigint,
  gamestasovasousemen bigint,
  avesde1dia bigint,
  adulto_1 bigint,
  recriada bigint,
  ovosferteis bigint,
  juveniladulto bigint,
  sementes bigint,
  ate12meses bigint,
  acima12meses bigint,
  outrasespecies bigint,
  recriado bigint,
  iniciado bigint,
  criada bigint,
  imago bigint,
  girino bigint,
  ovos bigint,
  repteisnaohidrobios bigint,
  machoreprodutorcachaco bigint,
  femeamatriz bigint,
  macholeitao bigint,
  femealeitao bigint,
  sexoidadenaorelevante bigint,
  adultofemea bigint,
  adultomacho bigint,
  ovosfemea bigint,
  ovosmacho bigint,
  jovensmacho bigint,
  jovensfemea bigint,
  uforigem text,
  codmunicipioorigem bigint,
  nomemunicipioorigem text,
  cpfcnpjorigem bigint,
  nomepessoaorigem text,
  codincra text,
  codpropestaborigem bigint,
  nomeorigem text,
  ufdestino text,
  codmunicipiodestino bigint,
  nomemunicipiodestino text,
  cpfcnpjdestino bigint,
  nomepessoadestino text,
  nrsim bigint,
  nrsif bigint,
  nrsie bigint,
  codpropestabdestino bigint,
  produtordestino text,
  cdlocalforaestado text,
  emissor text
);

-- Índices para o painel (filtros por data, espécie, origem e destino)
create index if not exists gta_dataemissao_idx on adagri.gta (dataemissao);
create index if not exists gta_especie_idx     on adagri.gta (especie);
create index if not exists gta_finalidade_idx  on adagri.gta (finalidade);
create index if not exists gta_origem_idx      on adagri.gta (codmunicipioorigem);
create index if not exists gta_ufdestino_idx   on adagri.gta (ufdestino);

-- Segurança (LGPD): a tabela tem CPF/CNPJ e nomes de pessoas.
-- Com RLS ligado e sem política, ninguém lê pela chave pública (anon).
alter table adagri.gta enable row level security;
